services:
  redis-lite:
    image: devam246/redis-lite:latest

    container_name: redis-lite

    restart: unless-stopped

    ports:
      - "8080:8080"

    volumes:
      - ./data:/data

    environment:
      AOF_PATH: /data/appendonly.aof
      APPENDONLY: "yes"